version: '3.8'

services:
  backend:
    build:
      context: ./backend
    environment:
      PORT: 8080
      DATABASE_URL: mongodb+srv://joelvegas:Ia72S4axkrdrwYdK@cluster0.ftus1wu.mongodb.net/?retryWrites=true&w=majority
  
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
